### PR TITLE
fix: link to train.ipynb

### PR DESCRIPTION
**Pull request by AlexXi19**
Fixed broken link to `train.ipynb`. 

Related issue: https://github.com/tensorchord/envd-docs/issues/184

### CODE REVIEW

**Review by gaocegege — APPROVED** [review]
LGTM :+1:
/lgtm

Thanks for your contribution! :tada: :+1:

**Comment by gaocegege** [comment]
Please sign the DCO. You can use `git commit -s` or use the UI to sign https://github.com/tensorchord/envd-docs/pull/186/checks?check_run_id=9407352965

**Comment by AlexXi19** [comment]
> Please sign the DCO. You can use `git commit -s` or use the UI to sign https://github.com/tensorchord/envd-docs/pull/186/checks?check_run_id=9407352965

Just followed the instructions in the link to rebase with a sign off and a force push, thanks for letting me know!

**Comment by gaocegege** [comment]
/lgtm

Thanks for your contribution! :tada: :+1:

**Pull request merged**
