### PR TITLE
feat: blog page

### PR DESCRIPTION
**Pull request by Sepush**
Signed-off-by: Sepush <sepush@outlook.com>

- when you add the first post to the blog you need add the default link to the 
`docs/.vitepress/config.ts` `nav`
image
- when add new post you should do following the readme blog

the Blog page will looks like
image

### CODE REVIEW

**Comment by VoVAllen** [comment]
I cannot click the `blog` button on the netlify preview page. Is this a netlify bug?

**Comment by Sepush** [comment]
> I cannot click the `blog` button on the netlify preview page. Is this a netlify bug?
no it's not a bug
because we don't have the first post so I leave the link blank
once we have the fisrt post and fill it it will be OK.
image

**Comment by gaocegege** [comment]
Could we please add a welcome post to verify it the blog works?

**Comment by Sepush** [comment]
> Could we add a welcome post to verify it the blog works?

added

**Comment by gaocegege** [comment]
Thanks for your contribution! :tada: :+1:

**Pull request merged**
