### PR TITLE
Feat: Add usage of conda configuration in envd

### PR DESCRIPTION
**Pull request by popfido**
Try to add corresponding documents on how to configure conda according to envd's [Issue291](https://github.com/tensorchord/envd/issues/291) and [PR293](https://github.com/tensorchord/envd/pull/293).

### CODE REVIEW

**Comment by gaocegege** [comment]
Wow! Great thanks!

While, the doc is actually auto-generated from https://github.com/tensorchord/envd/tree/main/envd/api

We parse the python package there and generate the API doc. Would you mind updating the code in https://github.com/tensorchord/envd/tree/main/envd/api ?

Or I can merge it and then update the code later, it also works for me.

**Comment by popfido** [comment]
@gaocegege Oh when I found there is no documentation about conda configuration parts, the "Edit this page" button leads me to this project so I thought I need to manually add documentation on that. Ok I'll update the code in https://github.com/tensorchord/envd/tree/main/envd/api and making a simple PR.

**Comment by popfido** [comment]
@gaocegege So this PR should be closed?

**Comment by gaocegege** [comment]
Sorry, we do not have a guide to contributing docs now. Yep, we can close the PR safely.

After your PR to envd repository is merged, we will regenerate the doc and file a PR here.

**Comment by popfido** [comment]
@gaocegege Okay. I make an [PR351](https://github.com/tensorchord/envd/pull/351) in the main project

**Pull request closed without merging**
