### PR TITLE
docs(zh): add translation

### PR DESCRIPTION
**Pull request by suyanhanx**
Finished the Chinese translation of the remaining pages. 
https://github.com/tensorchord/envd/issues/481

### CODE REVIEW

**Comment by gaocegege** [comment]
```
9:03:44 PM: (!) Found dead link /developer/development in file /opt/build/repo/docs-zh/community/contributing.md
9:03:44 PM: If it is intended, you can use:
9:03:44 PM:     <a href="/developer/development" target="_blank" rel="noreferrer">/developer/development</a>
9:03:45 PM: 
9:03:45 PM: (!) Found dead link /developer/development in file /opt/build/repo/docs-zh/community/contributing.md
9:03:45 PM: If it is intended, you can use:
9:03:45 PM:     <a href="/developer/development" target="_blank" rel="noreferrer">/developer/development</a>
9:03:49 PM: [vitepress] One or more pages contain dead links.
```

**Comment by gaocegege** [comment]
Thanks for your contribution! :tada: :+1:

Please fix the dead links

**Comment by suyanhanx** [comment]
The dead link is fixed.

**Comment by gaocegege** [comment]
Thanks! I am merging it

**Pull request merged**
